package cpu

var mainOpcodes = [256]Opcode{
	// Arithematic
	// 0x05: {Fn: (*CPU).InstrARITH_Dec_B, Mnemonic: "DEC B"},
	// 0x0D: {Fn: (*CPU).InstrARITH_Dec_C, Mnemonic: "DEC C"},

	// LOAD OPCODES
	0x00: {Fn: (*CPU).InstrNop, Mnemonic: "NOP"},
	0x01: {Fn: (*CPU).InstrLD_BC_d16, Mnemonic: "LD BC, d16"},
	0x02: {Fn: (*CPU).InstrLD_BC_ad_A, Mnemonic: "LD (BC), A"},
	0x06: {Fn: (*CPU).InstrLD_B_d8, Mnemonic: "LD B, d8"},
	0x08: {Fn: (*CPU).InstrLD_a16_SP, Mnemonic: "LD (a16), SP"},
	0x0A: {Fn: (*CPU).InstrLD_A_BC_ad, Mnemonic: "LD A, (BC)"},
	0x0E: {Fn: (*CPU).InstrLD_C_d8, Mnemonic: "LD C, d8"},
	0x11: {Fn: (*CPU).InstrLD_DE_d16, Mnemonic: "LD DE, d16"},
	0x12: {Fn: (*CPU).InstrLD_DE_ad_A, Mnemonic: "LD [DE], A"},
	0x16: {Fn: (*CPU).InstrLD_D_d8, Mnemonic: "LD D, d8"},
	0x1A: {Fn: (*CPU).InstrLD_A_DE_ad, Mnemonic: "LD A, [DE]"},
	0x1E: {Fn: (*CPU).InstrLD_E_d8, Mnemonic: "LD E, d8"},
	0x21: {Fn: (*CPU).InstrLD_HL_d16, Mnemonic: "LD HL, d16"},
	0x22: {Fn: (*CPU).InstrLD_HL_ad_INC_A, Mnemonic: "LD (HL+), A"},
	0x26: {Fn: (*CPU).InstrLD_H_d8, Mnemonic: "LD H, d8"},
	0x2A: {Fn: (*CPU).InstrLD_A_HL_ad_INC, Mnemonic: "LD A, (HL+)"},
	0x2E: {Fn: (*CPU).InstrLD_L_d8, Mnemonic: "LD L, d8"},
	0x31: {Fn: (*CPU).InstrLD_SP_d16, Mnemonic: "LD SP, d16"},
	0x32: {Fn: (*CPU).InstrLD_HL_ad_DEC_A, Mnemonic: "LD (HL-), A"},
	0x36: {Fn: (*CPU).InstrLD_HL_ad_d8, Mnemonic: "LD (HL) d8"},
	0x3A: {Fn: (*CPU).InstrLD_A_HL_ad_DEC, Mnemonic: "LD A, (HL-)"},
	0x3E: {Fn: (*CPU).InstrLD_A_d8, Mnemonic: "LD A d8"},
	0x40: {},
	0x41: {},
	0x42: {},
	0x44: {},
	0x45: {},
	0x46: {},
	0x47: {},
	0x48: {},
	0x49: {},
	0x4A: {},
	0x4B: {},
	0x4C: {},
	0x4D: {},
	0x4E: {},
	0x4F: {},
	0x50: {},
	0x51: {},
	0x52: {},
	0x54: {},
	0x55: {},
	0x56: {},
	0x57: {},
	0x58: {},
	0x59: {},
	0x5A: {},
	0x5B: {},
	0x5C: {},
	0x5D: {},
	0x5E: {},
	0x5F: {},
	0x60: {},
	0x61: {},
	0x62: {},
	0x64: {},
	0x65: {},
	0x66: {},
	0x67: {},
	0x68: {},
	0x69: {},
	0x6A: {},
	0x6B: {},
	0x6C: {},
	0x6D: {},
	0x6E: {},
	0x6F: {},
	0x70: {},
	0x71: {},
	0x72: {},
	0x74: {},
	0x75: {},
	0x77: {},
	0x78: {Fn: (*CPU).InstrLD_A_B, Mnemonic: "LD A B"},
	0x79: {},
	0x7A: {},
	0x7B: {},
	0x7C: {},
	0x7D: {},
	0x7E: {},
	0x7F: {},
	0xE0: {Fn: (*CPU).InstrLDH_a8_ad_A, Mnemonic: "LD (a8) A"},
	0xE2: {Fn: (*CPU).InstrLD_C_ad_A, Mnemonic: "LD (C) A"},
	0xEA: {Fn: (*CPU).InstrLD_a16_ad_A, Mnemonic: "LD (a16), A"},
	0xF0: {Fn: (*CPU).InstrLDH_A_a8, Mnemonic: "LD (a8) A"},
	0xF2: {Fn: (*CPU).InstrLD_A_C_Ad, Mnemonic: "LD A (C)"},
	0xF8: {},
	0xF9: {},
	0xFA: {},

	//Inc / Dec
	0x03: {Fn: (*CPU).INC_BC, Mnemonic: "INC BC"},
	0x13: {Fn: (*CPU).INC_DE, Mnemonic: "INC DE"},
	0x23: {Fn: (*CPU).INC_HL, Mnemonic: "INC HL"},
	0x33: {Fn: (*CPU).INC_SP, Mnemonic: "INC SP"},
	0x04: {Fn: (*CPU).INC_B, Mnemonic: "INC B"},
	0x14: {Fn: (*CPU).INC_D, Mnemonic: "INC D"},
	0x24: {Fn: (*CPU).INC_H, Mnemonic: "INC H"},
	0x34: {Fn: (*CPU).INC_HL_ad, Mnemonic: "INC (HL)"},
	0x05: {Fn: (*CPU).DEC_B, Mnemonic: "DEC B"},
	0x15: {Fn: (*CPU).DEC_D, Mnemonic: "DEC D"},
	0x25: {Fn: (*CPU).DEC_H, Mnemonic: "DEC H"},
	0x35: {Fn: (*CPU).DEC_HL_ad, Mnemonic: "DEC (HL)"},
	0x0B: {Fn: (*CPU).DEC_BC, Mnemonic: "DEC BC"},
	0x1B: {Fn: (*CPU).DEC_DE, Mnemonic: "DEC DE"},
	0x2B: {Fn: (*CPU).DEC_HL, Mnemonic: "DEC HL"},
	0x3B: {Fn: (*CPU).DEC_SP, Mnemonic: "DEC SP"},
	0x0C: {Fn: (*CPU).INC_C, Mnemonic: "INC C"},
	0x1C: {Fn: (*CPU).INC_E, Mnemonic: "INC E"},
	0x2C: {Fn: (*CPU).INC_L, Mnemonic: "INC L"},
	0x3C: {Fn: (*CPU).INC_A, Mnemonic: "INC A"},
	0x0D: {Fn: (*CPU).DEC_C, Mnemonic: "DEC C"},
	0x1D: {Fn: (*CPU).DEC_E, Mnemonic: "DEC E"},
	0x2D: {Fn: (*CPU).DEC_L, Mnemonic: "DEC L"},
	0x3D: {Fn: (*CPU).DEC_A, Mnemonic: "DEC A"},

	// ADD
	0x80: {},
	0x81: {},
	0x82: {},
	0x83: {},
	0x84: {},
	0x85: {},
	0x86: {},
	0x87: {},

	// ADC
	0x88: {},
	0x89: {},
	0x8A: {},
	0x8B: {},
	0x8C: {},
	0x8D: {},
	0x8E: {},
	0x8F: {},

	// SUB
	0x90: {},
	0x91: {},
	0x92: {},
	0x93: {},
	0x94: {},
	0x95: {},
	0x96: {},
	0x97: {},

	// SBC
	0x98: {},
	0x99: {},
	0x9A: {},
	0x9B: {},
	0x9C: {},
	0x9D: {},
	0x9E: {},
	0x9F: {},

	// AND
	0xA0: {},
	0xA1: {},
	0xA2: {},
	0xA3: {},
	0xA4: {},
	0xA5: {},
	0xA6: {},
	0xA7: {},

	// XOR
	0xA8: {},
	0xA9: {},
	0xAA: {},
	0xAB: {},
	0xAC: {},
	0xAD: {},
	0xAE: {},
	0xAF: {Fn: (*CPU).InstrLOGIC_XOR_A, Mnemonic: "XOR A"},

	// OR
	0xB0: {},
	0xB1: {},
	0xB2: {},
	0xB3: {},
	0xB4: {},
	0xB5: {},
	0xB6: {},
	0xB7: {},

	//CP
	0xB8: {Fn: (*CPU).InstrLOGIC_CP_B, Mnemonic: "CP B"},
	0xB9: {Fn: (*CPU).InstrLOGIC_CP_C, Mnemonic: "CP C"},
	0xBA: {Fn: (*CPU).InstrLOGIC_CP_D, Mnemonic: "CP D"},
	0xBB: {Fn: (*CPU).InstrLOGIC_CP_E, Mnemonic: "CP E"},
	0xBC: {Fn: (*CPU).InstrLOGIC_CP_H, Mnemonic: "CP H"},
	0xBD: {Fn: (*CPU).InstrLOGIC_CP_L, Mnemonic: "CP L"},
	0xBE: {Fn: (*CPU).InstrLOGIC_CP_HL_ad, Mnemonic: "CP (HL)"},
	0xBF: {Fn: (*CPU).InstrLOGIC_CP_A, Mnemonic: "CP A"},
	0xFE: {Fn: (*CPU).InstrLOGIC_CP_d8, Mnemonic: "CP d8"},

	// Move Instructions STACK:Pop
	0xC1: {Fn: (*CPU).InstrSTACK_POP_BC, Mnemonic: "POP BC"},
	0xC5: {Fn: (*CPU).InstrSTACK_PUSH_BC, Mnemonic: "PUSH BC"},
	0xD1: {Fn: (*CPU).InstrSTACK_POP_DE, Mnemonic: "POP DE"},
	0xD5: {Fn: (*CPU).InstrSTACK_PUSH_DE, Mnemonic: "PUSH DE"},
	0xE1: {Fn: (*CPU).InstrSTACK_POP_HL, Mnemonic: "POP HL"},
	0xE5: {Fn: (*CPU).InstrSTACK_PUSH_HL, Mnemonic: "PUSH HL"},
	0xF1: {Fn: (*CPU).InstrSTACK_POP_AF, Mnemonic: "POP AF"},
	0xF5: {Fn: (*CPU).InstrSTACK_PUSH_AF, Mnemonic: "PUSH AF"},

	//Jumps
	0x20: {Fn: (*CPU).JumpRelativeNotZero, Mnemonic: "JR NZ, r8"},
	0x30: {Fn: (*CPU).JumpRelativeNotCarry, Mnemonic: "JR NC, r8"},
	0x28: {Fn: (*CPU).JumpRelativeZero, Mnemonic: "JR Z, r8"},
	0x38: {Fn: (*CPU).JumpRelativeCarry, Mnemonic: "JR C, r8"},
	0x18: {Fn: (*CPU).JumpRelative, Mnemonic: "JR r8"},
	0xCA: {Fn: (*CPU).JumpAbsoluteNotZero, Mnemonic: "JP NZ a16"},
	0xDA: {Fn: (*CPU).JumpAbsoluteNotCarry, Mnemonic: "JP NC a16"},
	0xC2: {Fn: (*CPU).JumpAbsoluteZero, Mnemonic: "JP Z 16"},
	0xD2: {Fn: (*CPU).JumpAbsoluteCarry, Mnemonic: "JP C a16"},
	0xC3: {Fn: (*CPU).JumpAbsolute, Mnemonic: "JP a16"},
	0xE9: {Fn: (*CPU).JumpAbsoluteHL_ad, Mnemonic: "JP (HL)"},

	// RET
	0xC0: {Fn: (*CPU).RET_NZ, Mnemonic: "RET_NZ"},
	0xD0: {Fn: (*CPU).RET_NC, Mnemonic: "RET NC"},
	0xC8: {Fn: (*CPU).RET_Z, Mnemonic: "RET Z"},
	0xD8: {Fn: (*CPU).RET_C, Mnemonic: "RET C"},
	0xC9: {Fn: (*CPU).RET, Mnemonic: "RET"},
	0xD9: {Fn: (*CPU).RETI, Mnemonic: "RETI"},

	// CALL
	0xC4: {Fn: (*CPU).CALL_NZ, Mnemonic: "CALL_NZ"},
	0xD4: {Fn: (*CPU).CALL_NC, Mnemonic: "CALL_NC"},
	0xCC: {Fn: (*CPU).CALL_Z, Mnemonic: "CALL_Z"},
	0xDC: {Fn: (*CPU).CALL_C, Mnemonic: "CALL_C"},
	0xCD: {Fn: (*CPU).CALL, Mnemonic: "CALL"},

	// RST
	0xC7: {Fn: (*CPU).RST_00H, Mnemonic: "RST_00H"},
	0xD7: {Fn: (*CPU).RST_10H, Mnemonic: "RST_10H"},
	0xE7: {Fn: (*CPU).RST_20H, Mnemonic: "RST_20H"},
	0xF7: {Fn: (*CPU).RST_30H, Mnemonic: "RST_30H"},
	0xCF: {Fn: (*CPU).RST_08H, Mnemonic: "RST_08H"},
	0xDF: {Fn: (*CPU).RST_18H, Mnemonic: "RST_18H"},
	0xEF: {Fn: (*CPU).RST_28H, Mnemonic: "RST_28H"},
	0xFF: {Fn: (*CPU).RST_38H, Mnemonic: "RST_38H"},

	// Control
	0x10: {Fn: (*CPU).InstrCONT_STOP, Mnemonic: "STOP"},
	0x76: {Fn: (*CPU).InstrCONT_HALT, Mnemonic: "HALT"},
	0xF3: {Fn: (*CPU).InstrCONT_DI, Mnemonic: "DI"},
	0xFB: {Fn: (*CPU).InstrCONT_EI, Mnemonic: "EI"},
}

/*
OPCODE: 0x00
DESCRIPTION: No operation
CYCLES: 4
*/
func (cpu *CPU) InstrNop() int {
	return 4
}
