package cpu

var mainOpcodes = [256]Opcode{
	// LOAD OPCODES
	0x00: {Fn: (*CPU).InstrNop, Mnemonic: "NOP"},
	0x01: {Fn: (*CPU).InstrLD_BC_d16, Mnemonic: "LD BC, d16"},
	0x02: {Fn: (*CPU).InstrLD_BC_ad_A, Mnemonic: "LD (BC), A"},
	0x06: {Fn: (*CPU).InstrLD_B_d8, Mnemonic: "LD B, d8"},
	0x08: {Fn: (*CPU).InstrLD_a16_SP, Mnemonic: "LD (a16), SP"},
	0x0A: {Fn: (*CPU).InstrLD_A_BC_ad, Mnemonic: "LD A, (BC)"},
	0x0E: {Fn: (*CPU).InstrLD_C_d8, Mnemonic: "LD C, d8"},
	0x11: {Fn: (*CPU).InstrLD_DE_d16, Mnemonic: "LD DE, d16"},
	0x12: {Fn: (*CPU).InstrLD_DE_ad_A, Mnemonic: "LD [DE], A"},
	0x16: {Fn: (*CPU).InstrLD_D_d8, Mnemonic: "LD D, d8"},
	0x1A: {Fn: (*CPU).InstrLD_A_DE_ad, Mnemonic: "LD A, [DE]"},
	0x1E: {Fn: (*CPU).InstrLD_E_d8, Mnemonic: "LD E, d8"},
	0x21: {Fn: (*CPU).InstrLD_HL_d16, Mnemonic: "LD HL, d16"},
	0x22: {Fn: (*CPU).InstrLD_HL_ad_INC_A, Mnemonic: "LD (HL+), A"},
	0x26: {Fn: (*CPU).InstrLD_H_d8, Mnemonic: "LD H, d8"},
	0x2A: {Fn: (*CPU).InstrLD_A_HL_ad_INC, Mnemonic: "LD A, (HL+)"},
	0x2E: {Fn: (*CPU).InstrLD_L_d8, Mnemonic: "LD L, d8"},
	0x31: {Fn: (*CPU).InstrLD_SP_d16, Mnemonic: "LD SP, d16"},
	0x32: {Fn: (*CPU).InstrLD_HL_ad_DEC_A, Mnemonic: "LD (HL-), A"},
	0x36: {Fn: (*CPU).InstrLD_HL_ad_d8, Mnemonic: "LD (HL) d8"},
	0x3A: {Fn: (*CPU).InstrLD_A_HL_ad_DEC, Mnemonic: "LD A, (HL-)"},
	0x3E: {Fn: (*CPU).InstrLD_A_d8, Mnemonic: "LD A d8"},
	0x40: {Fn: (*CPU).InstrLD_B_B, Mnemonic: "LD B B"},
	0x41: {Fn: (*CPU).InstrLD_B_C, Mnemonic: "LD B C"},
	0x42: {Fn: (*CPU).InstrLD_B_D, Mnemonic: "LD B D"},
	0x43: {Fn: (*CPU).InstrLD_B_E, Mnemonic: "LD B E"},
	0x44: {Fn: (*CPU).InstrLD_B_H, Mnemonic: "LD B H"},
	0x45: {Fn: (*CPU).InstrLD_B_L, Mnemonic: "LD B L"},
	0x46: {Fn: (*CPU).InstrLD_B_HL_ad, Mnemonic: "LD B (HL)"},
	0x47: {Fn: (*CPU).InstrLD_B_A, Mnemonic: "LD B A"},
	0x48: {Fn: (*CPU).InstrLD_C_B, Mnemonic: "LD C B"},
	0x49: {Fn: (*CPU).InstrLD_C_C, Mnemonic: "LD C C"},
	0x4A: {Fn: (*CPU).InstrLD_C_D, Mnemonic: "LD C D"},
	0x4B: {Fn: (*CPU).InstrLD_C_E, Mnemonic: "LD C E"},
	0x4C: {Fn: (*CPU).InstrLD_C_H, Mnemonic: "LD C H"},
	0x4D: {Fn: (*CPU).InstrLD_C_L, Mnemonic: "LD C L"},
	0x4E: {Fn: (*CPU).InstrLD_C_HL_ad, Mnemonic: "LD C (HL)"},
	0x4F: {Fn: (*CPU).InstrLD_C_A, Mnemonic: "LD C A"},
	0x50: {Fn: (*CPU).InstrLD_D_B, Mnemonic: "LD D B"},
	0x51: {Fn: (*CPU).InstrLD_D_C, Mnemonic: "LD D C"},
	0x52: {Fn: (*CPU).InstrLD_D_D, Mnemonic: "LD D D"},
	0x53: {Fn: (*CPU).InstrLD_D_E, Mnemonic: "LD D E"},
	0x54: {Fn: (*CPU).InstrLD_D_H, Mnemonic: "LD D H"},
	0x55: {Fn: (*CPU).InstrLD_D_L, Mnemonic: "LD D L"},
	0x56: {Fn: (*CPU).InstrLD_D_HL_ad, Mnemonic: "LD D (HL)"},
	0x57: {Fn: (*CPU).InstrLD_D_A, Mnemonic: "LD D A"},
	0x58: {Fn: (*CPU).InstrLD_E_B, Mnemonic: "LD E B"},
	0x59: {Fn: (*CPU).InstrLD_E_C, Mnemonic: "LD E C"},
	0x5A: {Fn: (*CPU).InstrLD_E_D, Mnemonic: "LD E D"},
	0x5B: {Fn: (*CPU).InstrLD_E_E, Mnemonic: "LD E E"},
	0x5C: {Fn: (*CPU).InstrLD_E_H, Mnemonic: "LD E H"},
	0x5D: {Fn: (*CPU).InstrLD_E_L, Mnemonic: "LD E L"},
	0x5E: {Fn: (*CPU).InstrLD_E_HL_ad, Mnemonic: "LD E (HL)"},
	0x5F: {Fn: (*CPU).InstrLD_E_A, Mnemonic: "LD E A"},
	0x60: {Fn: (*CPU).InstrLD_H_B, Mnemonic: "LD H B"},
	0x61: {Fn: (*CPU).InstrLD_H_C, Mnemonic: "LD H C"},
	0x62: {Fn: (*CPU).InstrLD_H_D, Mnemonic: "LD H D"},
	0x63: {Fn: (*CPU).InstrLD_H_E, Mnemonic: "LD H E"},
	0x64: {Fn: (*CPU).InstrLD_H_H, Mnemonic: "LD H H"},
	0x65: {Fn: (*CPU).InstrLD_H_L, Mnemonic: "LD H L"},
	0x66: {Fn: (*CPU).InstrLD_H_HL_ad, Mnemonic: "LD H (HL)"},
	0x67: {Fn: (*CPU).InstrLD_H_A, Mnemonic: "LD H A"},
	0x68: {Fn: (*CPU).InstrLD_L_B, Mnemonic: "LD L B"},
	0x69: {Fn: (*CPU).InstrLD_L_C, Mnemonic: "LD L C"},
	0x6A: {Fn: (*CPU).InstrLD_L_D, Mnemonic: "LD L D"},
	0x6B: {Fn: (*CPU).InstrLD_L_E, Mnemonic: "LD L E"},
	0x6C: {Fn: (*CPU).InstrLD_L_H, Mnemonic: "LD L H"},
	0x6D: {Fn: (*CPU).InstrLD_L_L, Mnemonic: "LD L L"},
	0x6E: {Fn: (*CPU).InstrLD_L_HL_ad, Mnemonic: "LD L (HL)"},
	0x6F: {Fn: (*CPU).InstrLD_L_A, Mnemonic: "LD L A"},
	0x70: {Fn: (*CPU).InstrLD_HL_ad_B, Mnemonic: "LD (HL) B"},
	0x71: {Fn: (*CPU).InstrLD_HL_ad_C, Mnemonic: "LD (HL) C"},
	0x72: {Fn: (*CPU).InstrLD_HL_ad_D, Mnemonic: "LD (HL) D"},
	0x73: {Fn: (*CPU).InstrLD_HL_ad_E, Mnemonic: "LD (HL) E"},
	0x74: {Fn: (*CPU).InstrLD_HL_ad_H, Mnemonic: "LD (HL) H"},
	0x75: {Fn: (*CPU).InstrLD_HL_ad_L, Mnemonic: "LD (HL) L"},
	0x77: {Fn: (*CPU).InstrLD_HL_ad_A, Mnemonic: "LD (HL) A"},
	0x78: {Fn: (*CPU).InstrLD_A_B, Mnemonic: "LD A B"},
	0x79: {Fn: (*CPU).InstrLD_A_C, Mnemonic: "LD A C"},
	0x7A: {Fn: (*CPU).InstrLD_A_D, Mnemonic: "LD A D"},
	0x7B: {Fn: (*CPU).InstrLD_A_E, Mnemonic: "LD A E"},
	0x7C: {Fn: (*CPU).InstrLD_A_H, Mnemonic: "LD A H"},
	0x7D: {Fn: (*CPU).InstrLD_A_L, Mnemonic: "LD A L"},
	0x7E: {Fn: (*CPU).InstrLD_A_HL_ad, Mnemonic: "LD A (HL)"},
	0x7F: {Fn: (*CPU).InstrLD_A_A, Mnemonic: "LD A A"},
	0xE0: {Fn: (*CPU).InstrLDH_a8_ad_A, Mnemonic: "LD (a8) A"},
	0xE2: {Fn: (*CPU).InstrLD_C_ad_A, Mnemonic: "LD (C) A"},
	0xEA: {Fn: (*CPU).InstrLD_a16_ad_A, Mnemonic: "LD (a16), A"},
	0xF0: {Fn: (*CPU).InstrLDH_A_a8, Mnemonic: "LD (a8) A"},
	0xF2: {Fn: (*CPU).InstrLD_A_C_Ad, Mnemonic: "LD A (C)"},
	0xF8: {Fn: (*CPU).InstrLD_HL_SP_r8, Mnemonic: "LD HL SP+r8"},
	0xF9: {Fn: (*CPU).InstrLD_SP_HL, Mnemonic: "LD SP HL"},
	0xFA: {Fn: (*CPU).InstrLD_A_a16_ad, Mnemonic: "LD A (a16)"},

	//Inc / Dec
	0x03: {Fn: (*CPU).INC_BC, Mnemonic: "INC BC"},
	0x13: {Fn: (*CPU).INC_DE, Mnemonic: "INC DE"},
	0x23: {Fn: (*CPU).INC_HL, Mnemonic: "INC HL"},
	0x33: {Fn: (*CPU).INC_SP, Mnemonic: "INC SP"},
	0x04: {Fn: (*CPU).INC_B, Mnemonic: "INC B"},
	0x14: {Fn: (*CPU).INC_D, Mnemonic: "INC D"},
	0x24: {Fn: (*CPU).INC_H, Mnemonic: "INC H"},
	0x34: {Fn: (*CPU).INC_HL_ad, Mnemonic: "INC (HL)"},
	0x05: {Fn: (*CPU).DEC_B, Mnemonic: "DEC B"},
	0x15: {Fn: (*CPU).DEC_D, Mnemonic: "DEC D"},
	0x25: {Fn: (*CPU).DEC_H, Mnemonic: "DEC H"},
	0x35: {Fn: (*CPU).DEC_HL_ad, Mnemonic: "DEC (HL)"},
	0x0B: {Fn: (*CPU).DEC_BC, Mnemonic: "DEC BC"},
	0x1B: {Fn: (*CPU).DEC_DE, Mnemonic: "DEC DE"},
	0x2B: {Fn: (*CPU).DEC_HL, Mnemonic: "DEC HL"},
	0x3B: {Fn: (*CPU).DEC_SP, Mnemonic: "DEC SP"},
	0x0C: {Fn: (*CPU).INC_C, Mnemonic: "INC C"},
	0x1C: {Fn: (*CPU).INC_E, Mnemonic: "INC E"},
	0x2C: {Fn: (*CPU).INC_L, Mnemonic: "INC L"},
	0x3C: {Fn: (*CPU).INC_A, Mnemonic: "INC A"},
	0x0D: {Fn: (*CPU).DEC_C, Mnemonic: "DEC C"},
	0x1D: {Fn: (*CPU).DEC_E, Mnemonic: "DEC E"},
	0x2D: {Fn: (*CPU).DEC_L, Mnemonic: "DEC L"},
	0x3D: {Fn: (*CPU).DEC_A, Mnemonic: "DEC A"},

	// ADD
	0x80: {Fn: (*CPU).ADD_B, Mnemonic: "ADD A B"},
	0x81: {Fn: (*CPU).ADD_C, Mnemonic: "ADD A C"},
	0x82: {Fn: (*CPU).ADD_D, Mnemonic: "ADD A D"},
	0x83: {Fn: (*CPU).ADD_E, Mnemonic: "ADD A E"},
	0x84: {Fn: (*CPU).ADD_H, Mnemonic: "ADD A L"},
	0x85: {Fn: (*CPU).ADD_L, Mnemonic: "ADD A L"},
	0x86: {Fn: (*CPU).ADD_HL_ad, Mnemonic: "ADD A (HL)"},
	0x87: {Fn: (*CPU).ADD_A, Mnemonic: "ADD A A"},
	0xC6: {Fn: (*CPU).ADD_d8, Mnemonic: "AND d8"},
	0xE8: {Fn: (*CPU).ADD_SP_r8, Mnemonic: "AND d8"},
	0x09: {Fn: (*CPU).ADD_HL_BC, Mnemonic: "AND HL BC"},
	0x19: {Fn: (*CPU).ADD_HL_DE, Mnemonic: "AND HL DE"},
	0x29: {Fn: (*CPU).ADD_HL_HL, Mnemonic: "AND HL HL"},
	0x39: {Fn: (*CPU).ADD_HL_SP, Mnemonic: "AND HL SP"},
	// ADC
	0x88: {Fn: (*CPU).ADC_B, Mnemonic: "ADC A B"},
	0x89: {Fn: (*CPU).ADC_C, Mnemonic: "ADC A C"},
	0x8A: {Fn: (*CPU).ADC_D, Mnemonic: "ADC A D"},
	0x8B: {Fn: (*CPU).ADC_E, Mnemonic: "ADC A E"},
	0x8C: {Fn: (*CPU).ADC_H, Mnemonic: "ADC A L"},
	0x8D: {Fn: (*CPU).ADC_L, Mnemonic: "ADC A L"},
	0x8E: {Fn: (*CPU).ADC_HL_ad, Mnemonic: "ADC A (HL)"},
	0x8F: {Fn: (*CPU).ADC_A, Mnemonic: "ADC A A"},
	0xCE: {Fn: (*CPU).ADC_d8, Mnemonic: "ANC d8"},

	// SUB
	0x90: {Fn: (*CPU).SUB_B, Mnemonic: "SUB B"},
	0x91: {Fn: (*CPU).SUB_C, Mnemonic: "SUB C"},
	0x92: {Fn: (*CPU).SUB_D, Mnemonic: "SUB D"},
	0x93: {Fn: (*CPU).SUB_E, Mnemonic: "SUB E"},
	0x94: {Fn: (*CPU).SUB_H, Mnemonic: "SUB L"},
	0x95: {Fn: (*CPU).SUB_L, Mnemonic: "SUB L"},
	0x96: {Fn: (*CPU).SUB_HL_ad, Mnemonic: "SUB (HL)"},
	0x97: {Fn: (*CPU).SUB_A, Mnemonic: "SUB A"},
	0xD6: {Fn: (*CPU).SUB_d8, Mnemonic: "SUB d8"},

	// SBC
	0x98: {Fn: (*CPU).SBC_B, Mnemonic: "SBC A B"},
	0x99: {Fn: (*CPU).SBC_C, Mnemonic: "SBC A C"},
	0x9A: {Fn: (*CPU).SBC_D, Mnemonic: "SBC A  D"},
	0x9B: {Fn: (*CPU).SBC_E, Mnemonic: "SBC A E"},
	0x9C: {Fn: (*CPU).SBC_H, Mnemonic: "SBC A L"},
	0x9D: {Fn: (*CPU).SBC_L, Mnemonic: "SBC A L"},
	0x9E: {Fn: (*CPU).SBC_HL_ad, Mnemonic: "SBC A (HL)"},
	0x9F: {Fn: (*CPU).SBC_A, Mnemonic: "SBC A A"},
	0xDE: {Fn: (*CPU).SBC_d8, Mnemonic: "SBC d8"},

	// AND
	0xA0: {Fn: (*CPU).InstrLOGIC_AND_B, Mnemonic: "AND B"},
	0xA1: {Fn: (*CPU).InstrLOGIC_AND_C, Mnemonic: "AND C"},
	0xA2: {Fn: (*CPU).InstrLOGIC_AND_D, Mnemonic: "AND D"},
	0xA3: {Fn: (*CPU).InstrLOGIC_AND_E, Mnemonic: "AND E"},
	0xA4: {Fn: (*CPU).InstrLOGIC_AND_H, Mnemonic: "AND H"},
	0xA5: {Fn: (*CPU).InstrLOGIC_AND_L, Mnemonic: "AND L"},
	0xA6: {Fn: (*CPU).InstrLOGIC_AND_HL_ad, Mnemonic: "AND (HL)"}, // return 8
	0xA7: {Fn: (*CPU).InstrLOGIC_AND_A, Mnemonic: "AND A"},
	0xE6: {Fn: (*CPU).InstrLOGIC_AND_d8, Mnemonic: "AND d8"},

	// XOR
	0xA8: {Fn: (*CPU).InstrLOGIC_XOR_B, Mnemonic: "XOR B"},
	0xA9: {Fn: (*CPU).InstrLOGIC_XOR_C, Mnemonic: "XOR C"},
	0xAA: {Fn: (*CPU).InstrLOGIC_XOR_D, Mnemonic: "XOR D"},
	0xAB: {Fn: (*CPU).InstrLOGIC_XOR_E, Mnemonic: "XOR E"},
	0xAC: {Fn: (*CPU).InstrLOGIC_XOR_H, Mnemonic: "XOR H"},
	0xAD: {Fn: (*CPU).InstrLOGIC_XOR_L, Mnemonic: "XOR L"},
	0xAE: {Fn: (*CPU).InstrLOGIC_XOR_HL_ad, Mnemonic: "XOR (HL)"}, // return 8
	0xAF: {Fn: (*CPU).InstrLOGIC_XOR_A, Mnemonic: "XOR A"},
	0xEE: {Fn: (*CPU).InstrLOGIC_XOR_d8, Mnemonic: "XOR d8"},

	// OR
	0xB0: {Fn: (*CPU).InstrLOGIC_OR_B, Mnemonic: "OR B"},
	0xB1: {Fn: (*CPU).InstrLOGIC_OR_C, Mnemonic: "OR C"},
	0xB2: {Fn: (*CPU).InstrLOGIC_OR_D, Mnemonic: "OR D"},
	0xB3: {Fn: (*CPU).InstrLOGIC_OR_E, Mnemonic: "OR E"},
	0xB4: {Fn: (*CPU).InstrLOGIC_OR_H, Mnemonic: "OR H"},
	0xB5: {Fn: (*CPU).InstrLOGIC_OR_L, Mnemonic: "OR L"},
	0xB6: {Fn: (*CPU).InstrLOGIC_OR_HL_ad, Mnemonic: "OR (HL)"}, // return 8
	0xB7: {Fn: (*CPU).InstrLOGIC_OR_A, Mnemonic: "OR A"},
	0xF6: {Fn: (*CPU).InstrLOGIC_OR_d8, Mnemonic: "OR d8"},

	//CP
	0xB8: {Fn: (*CPU).InstrLOGIC_CP_B, Mnemonic: "CP B"},
	0xB9: {Fn: (*CPU).InstrLOGIC_CP_C, Mnemonic: "CP C"},
	0xBA: {Fn: (*CPU).InstrLOGIC_CP_D, Mnemonic: "CP D"},
	0xBB: {Fn: (*CPU).InstrLOGIC_CP_E, Mnemonic: "CP E"},
	0xBC: {Fn: (*CPU).InstrLOGIC_CP_H, Mnemonic: "CP H"},
	0xBD: {Fn: (*CPU).InstrLOGIC_CP_L, Mnemonic: "CP L"},
	0xBE: {Fn: (*CPU).InstrLOGIC_CP_HL_ad, Mnemonic: "CP (HL)"}, // return 8
	0xBF: {Fn: (*CPU).InstrLOGIC_CP_A, Mnemonic: "CP A"},
	0xFE: {Fn: (*CPU).InstrLOGIC_CP_d8, Mnemonic: "CP d8"},

	//DAA
	0x27: {Fn: (*CPU).DAA, Mnemonic: "DAA"},
	//CPL
	0x2F: {Fn: (*CPU).CPL, Mnemonic: "CPL"},
	// SCF
	0x37: {Fn: (*CPU).SCF, Mnemonic: "SCF"},
	// CCF
	0x3F: {Fn: (*CPU).CCF, Mnemonic: "CCF"},
	// Move Instructions STACK:Pop
	0xC1: {Fn: (*CPU).InstrSTACK_POP_BC, Mnemonic: "POP BC"},
	0xC5: {Fn: (*CPU).InstrSTACK_PUSH_BC, Mnemonic: "PUSH BC"},
	0xD1: {Fn: (*CPU).InstrSTACK_POP_DE, Mnemonic: "POP DE"},
	0xD5: {Fn: (*CPU).InstrSTACK_PUSH_DE, Mnemonic: "PUSH DE"},
	0xE1: {Fn: (*CPU).InstrSTACK_POP_HL, Mnemonic: "POP HL"},
	0xE5: {Fn: (*CPU).InstrSTACK_PUSH_HL, Mnemonic: "PUSH HL"},
	0xF1: {Fn: (*CPU).InstrSTACK_POP_AF, Mnemonic: "POP AF"},
	0xF5: {Fn: (*CPU).InstrSTACK_PUSH_AF, Mnemonic: "PUSH AF"},

	//Jumps
	0x20: {Fn: (*CPU).JumpRelativeNotZero, Mnemonic: "JR NZ, r8"},
	0x30: {Fn: (*CPU).JumpRelativeNotCarry, Mnemonic: "JR NC, r8"},
	0x28: {Fn: (*CPU).JumpRelativeZero, Mnemonic: "JR Z, r8"},
	0x38: {Fn: (*CPU).JumpRelativeCarry, Mnemonic: "JR C, r8"},
	0x18: {Fn: (*CPU).JumpRelative, Mnemonic: "JR r8"},
	0xCA: {Fn: (*CPU).JumpAbsoluteNotZero, Mnemonic: "JP NZ a16"},
	0xDA: {Fn: (*CPU).JumpAbsoluteNotCarry, Mnemonic: "JP NC a16"},
	0xC2: {Fn: (*CPU).JumpAbsoluteZero, Mnemonic: "JP Z 16"},
	0xD2: {Fn: (*CPU).JumpAbsoluteCarry, Mnemonic: "JP C a16"},
	0xC3: {Fn: (*CPU).JumpAbsolute, Mnemonic: "JP a16"},
	0xE9: {Fn: (*CPU).JumpAbsoluteHL_ad, Mnemonic: "JP (HL)"},

	// RET
	0xC0: {Fn: (*CPU).RET_NZ, Mnemonic: "RET_NZ"},
	0xD0: {Fn: (*CPU).RET_NC, Mnemonic: "RET NC"},
	0xC8: {Fn: (*CPU).RET_Z, Mnemonic: "RET Z"},
	0xD8: {Fn: (*CPU).RET_C, Mnemonic: "RET C"},
	0xC9: {Fn: (*CPU).RET, Mnemonic: "RET"},
	0xD9: {Fn: (*CPU).RETI, Mnemonic: "RETI"},

	// CALL
	0xC4: {Fn: (*CPU).CALL_NZ, Mnemonic: "CALL_NZ"},
	0xD4: {Fn: (*CPU).CALL_NC, Mnemonic: "CALL_NC"},
	0xCC: {Fn: (*CPU).CALL_Z, Mnemonic: "CALL_Z"},
	0xDC: {Fn: (*CPU).CALL_C, Mnemonic: "CALL_C"},
	0xCD: {Fn: (*CPU).CALL, Mnemonic: "CALL"},

	// RST
	0xC7: {Fn: (*CPU).RST_00H, Mnemonic: "RST_00H"},
	0xD7: {Fn: (*CPU).RST_10H, Mnemonic: "RST_10H"},
	0xE7: {Fn: (*CPU).RST_20H, Mnemonic: "RST_20H"},
	0xF7: {Fn: (*CPU).RST_30H, Mnemonic: "RST_30H"},
	0xCF: {Fn: (*CPU).RST_08H, Mnemonic: "RST_08H"},
	0xDF: {Fn: (*CPU).RST_18H, Mnemonic: "RST_18H"},
	0xEF: {Fn: (*CPU).RST_28H, Mnemonic: "RST_28H"},
	0xFF: {Fn: (*CPU).RST_38H, Mnemonic: "RST_38H"},

	// Control
	0x10: {Fn: (*CPU).InstrCONT_STOP, Mnemonic: "STOP"},
	0x76: {Fn: (*CPU).InstrCONT_HALT, Mnemonic: "HALT"},
	0xF3: {Fn: (*CPU).InstrCONT_DI, Mnemonic: "DI"},
	0xFB: {Fn: (*CPU).InstrCONT_EI, Mnemonic: "EI"},

	//Rotation
	0x07: {Fn: (*CPU).RLCA, Mnemonic: "RLCA"},
	0x0F: {Fn: (*CPU).RRCA, Mnemonic: "RRCA"},
	0x17: {Fn: (*CPU).RLA, Mnemonic: "RLA"},
	0x1F: {Fn: (*CPU).RRA, Mnemonic: "RRA"},
}

/*
OPCODE: 0x00
DESCRIPTION: No operation
CYCLES: 4
*/
func (cpu *CPU) InstrNop() int {
	return 4
}
