package cpu

var mainOpcodes = [256]Opcode{
	// Arithematic
	0x05: {Fn: (*CPU).InstrARITH_Dec_B, Mnemonic: "DEC B"},
	0x0D: {Fn: (*CPU).InstrARITH_Dec_C, Mnemonic: "DEC C"},

	// MOVE OPCODES
	0x00: {Fn: (*CPU).InstrNop, Mnemonic: "NOP"},
	// 0xCB: {Fn: (*CPU).InstrPrefixCB, Mnemonic: "PREFIX CB"}, Step function handles it
	0x01: {Fn: (*CPU).InstrLD_BC_d16, Mnemonic: "LD BC, d16"},
	0x02: {Fn: (*CPU).InstrLD_BC_ad_A, Mnemonic: "LD (BC), A"},
	0x06: {Fn: (*CPU).InstrLD_B_d8, Mnemonic: "LD B, d8"},
	0x08: {Fn: (*CPU).InstrLD_a16_SP, Mnemonic: "LD (a16), SP"},
	0x0A: {Fn: (*CPU).InstrLD_A_BC_ad, Mnemonic: "LD A, (BC)"},
	0x0E: {Fn: (*CPU).InstrLD_C_d8, Mnemonic: "LD C, d8"},
	0x11: {Fn: (*CPU).InstrLD_DE_d16, Mnemonic: "LD DE, d16"},
	0x12: {Fn: (*CPU).InstrLD_DE_ad_A, Mnemonic: "LD [DE], A"},
	0x16: {Fn: (*CPU).InstrLD_D_d8, Mnemonic: "LD D, d8"},
	0x1A: {Fn: (*CPU).InstrLD_A_DE_ad, Mnemonic: "LD A, [DE]"},
	0x1E: {Fn: (*CPU).InstrLD_E_d8, Mnemonic: "LD E, d8"},
	0x21: {Fn: (*CPU).InstrLD_HL_d16, Mnemonic: "LD HL, d16"},
	0x22: {Fn: (*CPU).InstrLD_HL_ad_INC_A, Mnemonic: "LD (HL+), A"},
	0x26: {},
	0x2E: {},
	0x2A: {Fn: (*CPU).InstrLD_A_HL_ad_INC, Mnemonic: "LD A, (HL+)"},
	0x31: {Fn: (*CPU).InstrLD_SP_d16, Mnemonic: "LD SP, d16"},
	0x32: {Fn: (*CPU).InstrLD_HL_ad_DEC_A, Mnemonic: "LD (HL-), A"},
	0x36: {Fn: (*CPU).InstrLD_HL_ad_d8, Mnemonic: "LD (HL) d8"},
	0x3A: {Fn: (*CPU).InstrLD_A_HL_ad_DEC, Mnemonic: "LD A, (HL-)"},
	0x3E: {Fn: (*CPU).InstrLD_A_d8, Mnemonic: "LD A d8"},
	0x40: {},
	0x41: {},
	0x42: {},
	0x44: {},
	0x45: {},
	0x46: {},
	0x47: {},
	0x48: {},
	0x49: {},
	0x4A: {},
	0x4B: {},
	0x4C: {},
	0x4D: {},
	0x4E: {},
	0x4F: {},
	0x50: {},
	0x51: {},
	0x52: {},
	0x54: {},
	0x55: {},
	0x56: {},
	0x57: {},
	0x58: {},
	0x59: {},
	0x5A: {},
	0x5B: {},
	0x5C: {},
	0x5D: {},
	0x5E: {},
	0x5F: {},
	0x60: {},
	0x61: {},
	0x62: {},
	0x64: {},
	0x65: {},
	0x66: {},
	0x67: {},
	0x68: {},
	0x69: {},
	0x6A: {},
	0x6B: {},
	0x6C: {},
	0x6D: {},
	0x6E: {},
	0x6F: {},
	0x70: {},
	0x71: {},
	0x72: {},
	0x74: {},
	0x75: {},
	// 0x76: Not Part of the Load instructions
	0x77: {},
	0x78: {},
	0x79: {},
	0x7A: {},
	0x7B: {},
	0x7C: {},
	0x7D: {},
	0x7E: {},
	0x7F: {},
	0xE0: {Fn: (*CPU).InstrLDH_a8_ad_A, Mnemonic: "LD (a8) A"},
	0xE2: {Fn: (*CPU).InstrLD_C_ad_A, Mnemonic: "LD (C) A"},
	0xEA: {Fn: (*CPU).InstrLD_a16_ad_A, Mnemonic: "LD (a16), A"},
	0xF0: {Fn: (*CPU).InstrLDH_A_a8, Mnemonic: "LD (a8) A"},
	0xF2: {Fn: (*CPU).InstrLD_A_C_Ad, Mnemonic: "LD A (C)"},
	0xFA: {},
	// Move Instructions STACK:Pop
	0xC1: {},
	0xD1: {},
	0xE1: {},
	0xF1: {},
	//Jumps
	0x20: {Fn: (*CPU).JumpRelativeNotZero, Mnemonic: "JR NZ, r8"},
	0x30: {Fn: (*CPU).JumpRelativeNotCarry, Mnemonic: "JR NC, r8"},
	0x28: {Fn: (*CPU).JumpRelativeZero, Mnemonic: "JR Z, r8"},
	0x38: {Fn: (*CPU).JumpRelativeCarry, Mnemonic: "JR C, r8"},
	0x18: {Fn: (*CPU).JumpRelative, Mnemonic: "JR r8"},
	0xCA: {Fn: (*CPU).JumpAbsoluteNotZero, Mnemonic: "JP NZ a16"},
	0xDA: {Fn: (*CPU).JumpAbsoluteNotCarry, Mnemonic: "JP NC a16"},
	0xC2: {Fn: (*CPU).JumpAbsoluteZero, Mnemonic: "JP 16"},
	0xD2: {Fn: (*CPU).JumpAbsoluteCarry, Mnemonic: "JP C a16"},
	0xC3: {Fn: (*CPU).JumpAbsolute, Mnemonic: "JP a16"},
	0xE9: {Fn: (*CPU).JumpAbsoluteHL_ad, Mnemonic: "JP (HL)"},
	// Move Instructions STACK:Push
	0xC5: {},
	0xD5: {},
	0xE5: {},
	0xF5: {},
	// Misc
	0xF8: {},
	0xF9: {},
	// Logical
	0xAF: {Fn: (*CPU).InstrLOGIC_XOR_A, Mnemonic: "XOR A"},
	0xFE: {Fn: (*CPU).InstrLOGIC_CP_d8, Mnemonic: "CP d8"},
	// Control
	0x10: {Fn: (*CPU).InstrCONT_STOP, Mnemonic: "STOP"},
	0x76: {Fn: (*CPU).InstrCONT_HALT, Mnemonic: "HALT"},
	0xF3: {Fn: (*CPU).InstrCONT_DI, Mnemonic: "DI"},
	0xFB: {Fn: (*CPU).InstrCONT_EI, Mnemonic: "EI"},
}

/*
OPCODE: 0x00
DESCRIPTION: No operation
CYCLES: 4
*/
func (cpu *CPU) InstrNop() int {
	return 4
}
